colors:
  # Default colors
  primary:
    background: '0x1a1b26'
    foreground: '0xc0caf5'

  # Normal colors
  normal:
    black:   '0x15161e'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xa9b1d6'

  # Bright colors
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xc0caf5'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdb4b4b' }
env: {
  # Needed for my 4k 32inch monitor
  # "WINIT_X11_SCALE_FACTOR": "2",
  "TERM": "xterm-256color"
}
font: {
  "normal": {
    "family": "Iosevka Fixed"
  },
  "size": 15
}
key_bindings: [
  {
    "action": "SpawnNewInstance",
    "key": "N",
    "mods": "Control|Shift"
  },
  {
    "key": "N",
    "mods": "Super"
    "action": "\x1bn",
  }
]
scrolling: {
  "history": 10000,
  "multiplier": 3
}
window: {
  "dynamic_padding": true,
  "dynamic_title": true,
  "opacity": 1,
  "padding": {
    "x": 5,
    "y": 5
  }
}
