[general]
import = ["local.toml"]

[terminal]
shell = { program="/usr/bin/env", args = ["zellij"] }

[env]
# This is needed for the font size to not double in X11
# With this, it looks more or less similar to wayland font size
WINIT_X11_SCALE_FACTOR = "1.0"

[font.normal]
family = "Iosevka Fixed"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[mouse.bindings]]
mouse = "Middle"
action = "None"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.99
blur = true
decorations_theme_variant = "Dark"
decorations = "None"

[window.padding]
x = 0
y = 0
