{
  "colors": {
    "bright": {
      "black": "0x414868",
      "blue": "0x7aa2f7",
      "cyan": "0x7dcfff",
      "green": "0x9ece6a",
      "magenta": "0xbb9af7",
      "red": "0xf7768e",
      "white": "0xc0caf5",
      "yellow": "0xe0af68"
    },
    "indexed_colors": [
      {
        "color": "0xff9e64",
        "index": 16
      },
      {
        "color": "0xdb4b4b",
        "index": 17
      }
    ],
    "normal": {
      "black": "0x1D202F",
      "blue": "0x7aa2f7",
      "cyan": "0x7dcfff",
      "green": "0x9ece6a",
      "magenta": "0xbb9af7",
      "red": "0xf7768e",
      "white": "0xa9b1d6",
      "yellow": "0xe0af68"
    },
    "primary": {
      "background": "0x24283b",
      "foreground": "0xc0caf5"
    }
  },
  "env": {
    # Needed for my 4k 32inch monitor
    # "WINIT_X11_SCALE_FACTOR": "2",
    "TERM": "xterm-256color"
  },
  "font": {
    "normal": {
      "family": "Iosevka Nerd Font"
    },
    "size": 14
  },
  "key_bindings": [
    {
      "action": "SpawnNewInstance",
      "key": "N",
      "mods": "Control|Shift"
    }
  ],
  "scrolling": {
    "history": 10000,
    "multiplier": 3
  },
  "window": {
    "dynamic_padding": true,
    "dynamic_title": true,
    "opacity": 1,
    "padding": {
      "x": 5,
      "y": 5
    }
  }
}
