[general]
import = ["local.toml"]
shell = "/usr/local/bin/zellij"

[env]
# This is needed for the font size to not double in X11
# With this, it looks more or less similar to wayland font size
WINIT_X11_SCALE_FACTOR = "1.0"

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[font.normal]
family = "Iosevka Fixed"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[mouse.bindings]]
mouse = "Middle"
action = "None"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.99
blur = true
decorations_theme_variant = "Dark"
decorations = "None"

[window.padding]
x = 5
y = 5
