#!/usr/bin/env bash
sudo pacman -S --needed	\
		fish \
		git					\
		neovim			\
		i3-gaps			\
		polybar			\
		sxhkd				\
		jq					\
		ttc-iosevka	\
		ttf-roboto  \
		ttf-liberation  \
		awesome-terminal-fonts \
		fd					\
		the_silver_searcher	\
		ripgrep			\
		htop				\
		fzf \
		nitrogen \
		pavucontrol \
		lxappearance \
		lxrandr      \
		rofi         \
		xcursor-vanilla-dmz \
		xsettingsd \
		gtk2fontsel \
		strace \
		gpicview \
		evince \
		keepassxc \
		keybase kbfs keybase-gui \
		libreoffice-still \
		telegram-desktop \
		starship \
		direnv \
		xsel \
		xclip \
		flameshot \
		\
		blueman									\
		networkmanager					\
		network-manager-applet 	\
		pcmanfm									\
		gvfs										\
		pipewire-pulse					\
		pipewire-alsa					\
		picom \
		xarchiver \
		;
